workflows:
    android-flutter:
        name: Android App with Flutter Module
        environment:
            flutter: stable
        scripts:
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/accounting/local.properties"
            - cd <your_flutter_module> && flutter pub get
            - cd <your_host_android_app> && ./gradlew assembleDebug
        artifacts:
            - <your_android_app>/app/build/outputs/**/**/*.apk
